[#1278] Fix test play.db.jpa.JPQLTest
[javac]
/home/travis/build/playframework/play1/framework/test-src/play/db/jpa/JPQLTest.java:20:
error: constructor JPQL in class JPQL cannot be applied to given types;
    [javac] 		jpql = new JPQL(null);
    [javac] 		       ^
    [javac]   required: no arguments
    [javac]   found: <null>